extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.to_ssa]
pipeline = [
    "bril2json",
    "./bril-opts --ssa",
    "bril2json",
    "brili -p {args}",
]

[runs.to_from_ssa]
pipeline = [
    "bril2json",
    "./bril-opts --ssa",
    "bril2json",
    "./from_ssa",
    "brili -p {args}",
]